// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.QuotesHistory.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class QuoteResponse
    {
        /// <summary>
        /// Initializes a new instance of the QuoteResponse class.
        /// </summary>
        public QuoteResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the QuoteResponse class.
        /// </summary>
        public QuoteResponse(bool isBuy, double price, System.DateTime timestamp, string assetPair = default(string))
        {
            AssetPair = assetPair;
            IsBuy = isBuy;
            Price = price;
            Timestamp = timestamp;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "assetPair")]
        public string AssetPair { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isBuy")]
        public bool IsBuy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "price")]
        public double Price { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "timestamp")]
        public System.DateTime Timestamp { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
